# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/python101',
                'doc_host': 'https://dolremi.github.io',
                'git_url': 'https://github.com/dolremi/python101',
                'lib_path': 'python101'},
  'syms': {}}
